services:
  # Web service
  - type: web
    name: flask-energy-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      flask db upgrade  # Run migrations before starting the app
    startCommand: gunicorn --config gunicorn_config.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: rwe-postgres
          property: connectionString
      - key: USERNAME
        sync: false  # Will be set manually in Render dashboard
      - key: PASSWORD
        sync: false  # Will be set manually in Render dashboard
      - key: PORT
        value: 5000
      - key: FLASK_APP  # Required for Flask CLI commands
        value: app

  # Scheduler worker service
  - type: worker
    name: flask-energy-scheduler
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python scheduler_service.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        sync: true  # Sync with web service
      - key: DATABASE_URL
        fromDatabase:
          name: rwe-postgres
          property: connectionString
      - key: USERNAME
        sync: true  # Sync with web service
      - key: PASSWORD
        sync: true  # Sync with web service

databases:
  - name: rwe-postgres
    databaseName: rwe_data
    user: rwe_user
    plan: free  # 1GB storage, sufficient for ~3 years
    ipAllowList: []  # Allow all IPs