"""add production table

Revision ID: 20240325152900
Revises: dfdfe7849931
Create Date: 2024-03-25 15:29:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20240325152900'  # Using timestamp-based ID
down_revision = 'dfdfe7849931'  # Your initial migration ID
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_data',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('datetime', sa.DateTime(), nullable=False),
        sa.Column('fueloil', sa.Float(), nullable=True),
        sa.Column('gasoil', sa.Float(), nullable=True),
        sa.Column('blackcoal', sa.Float(), nullable=True),
        sa.Column('lignite', sa.Float(), nullable=True),
        sa.Column('geothermal', sa.Float(), nullable=True),
        sa.Column('naturalgas', sa.Float(), nullable=True),
        sa.Column('river', sa.Float(), nullable=True),
        sa.Column('dammedhydro', sa.Float(), nullable=True),
        sa.Column('lng', sa.Float(), nullable=True),
        sa.Column('biomass', sa.Float(), nullable=True),
        sa.Column('naphta', sa.Float(), nullable=True),
        sa.Column('importcoal', sa.Float(), nullable=True),
        sa.Column('asphaltitecoal', sa.Float(), nullable=True),
        sa.Column('wind', sa.Float(), nullable=True),
        sa.Column('nuclear', sa.Float(), nullable=True),
        sa.Column('sun', sa.Float(), nullable=True),
        sa.Column('importexport', sa.Float(), nullable=True),
        sa.Column('total', sa.Float(), nullable=True),
        sa.Column('wasteheat', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('production_data')
    # ### end Alembic commands ### 