"""Add natural gas and imported coal heatmap tables

Revision ID: dc9103d3fe4b
Revises: 
Create Date: 2025-03-04 11:04:11.979028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc9103d3fe4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imported_coal_heatmap_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('plant_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('version', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'hour', 'plant_name', 'version', name='imported_coal_heatmap_data_date_hour_plant_name_version_key')
    )
    op.create_table('natural_gas_heatmap_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('plant_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('version', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'hour', 'plant_name', 'version', name='natural_gas_heatmap_data_date_hour_plant_name_version_key')
    )
    with op.batch_alter_table('hydro_heatmap_data', schema=None) as batch_op:
        batch_op.alter_column('version',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hydro_heatmap_data', schema=None) as batch_op:
        batch_op.alter_column('version',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    op.drop_table('natural_gas_heatmap_data')
    op.drop_table('imported_coal_heatmap_data')
    # ### end Alembic commands ###
